// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar pour le tutoriel, générée automatiquement
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Sidebar pour la Checklist de Conformité
  checklistSidebar: [
    {
      type: 'category',
      label: 'Checklist de Conformité',
      items: [
        'checklist/introduction',
        'checklist/acces-installation',
        'checklist/releve-compteurs',
        'checklist/rapport-conformite',
        'checklist/plans-schemas-électriques',
        'checklist/analyse-risques',
        'checklist/plans-issues-secours',
        'checklist/documentation-machines',
        'checklist/dossier-electrique',
      ],
    },
  ],
};

module.exports = sidebars;
