// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar pour le tutoriel, générée automatiquement
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Sidebar pour la Checklist de Conformité
  checklistSidebar: [
    {
      type: 'category',
      label: 'Checklist de Conformité',
      items: [
        { type: 'doc', id: 'checklist/introduction', label: 'Introduction' },
        { type: 'doc', id: 'checklist/acces-installation', label: 'Accès Installation' },
        { type: 'doc', id: 'checklist/identification-compteurs', label: 'Identification Compteurs' },
        { type: 'doc', id: 'checklist/rapport-conformite', label: 'Rapport de Conformité' },
        { type: 'doc', id: 'checklist/plans-schemas-electriques', label: 'Plans Électriques' },
        { type: 'doc', id: 'checklist/analyse-risques', label: 'Analyse des Risques' },
        { type: 'doc', id: 'checklist/luminaires-de-secours', label: 'Luminaires de Secours' },
        { type: 'doc', id: 'checklist/documentation-machines', label: 'Doc Machines' },
        { type: 'doc', id: 'checklist/dossier-electrique', label: 'Dossier Électrique' },
      ],
    },
  ],

  // Sidebar pour le Guide RGIE
  guideRGIESidebar: [
    {
      type: 'category',
      label: 'Guide RGIE',
      items: [
        { type: 'doc', id: 'guide-rgie/introduction', label: 'Introduction' },
        { type: 'doc', id: 'guide-rgie/partie-1-prescriptions-generales', label: 'Prescriptions Générales' },
        { type: 'doc', id: 'guide-rgie/partie-2-termes-definitions', label: 'Termes et Définitions' },
        { type: 'doc', id: 'guide-rgie/partie-3-determination-caracteristiques', label: 'Détermination des Caractéristiques' },
        { type: 'doc', id: 'guide-rgie/partie-4-mesures-protection', label: 'Mesures de Protection' },
        { type: 'doc', id: 'guide-rgie/partie-5-choix-mise-en-oeuvre', label: 'Choix et Mise en Œuvre' },
        { type: 'doc', id: 'guide-rgie/partie-6-controles-installations', label: 'Contrôles des Installations' },
        { type: 'doc', id: 'guide-rgie/partie-7-regles-installations-emplacements', label: 'Règles pour les Installations et Emplacements Spéciaux' },
        { type: 'doc', id: 'guide-rgie/partie-8-prescriptions-installations-existantes', label: 'Prescriptions pour Installations Existantes' },
        { type: 'doc', id: 'guide-rgie/partie-9-prescriptions-personnes', label: 'Prescriptions Générales à Observer' },
        { type: 'doc', id: 'guide-rgie/conclusion', label: 'Conclusion' },
      ],
    },
  ],

  // Sidebar pour les Infractions
  infractionsSidebar: [
    {
      type: 'category',
      label: 'Infractions Électriques',
      items: [
        { type: 'doc', id: 'infractions/introduction', label: 'Introduction' },
        { type: 'doc', id: 'infractions/schema-electriques-absents', label: 'Schémas Électriques Absents ou Non Conformes' },
        { type: 'doc', id: 'infractions/perte-electricite-isolation', label: 'Pertes d\'Électricité et Résistance à l\'Isolation' },
        { type: 'doc', id: 'infractions/resistance-terre-non-conforme', label: 'Résistance de Terre Non Conforme' },
        { type: 'doc', id: 'infractions/tableau-electrique-non-conforme', label: 'Tableau Électrique Non Conforme' },
        { type: 'doc', id: 'infractions/circuits-non-proteges-differentiel', label: 'Circuits Non Protégés par un Différentiel 30mA' },
        { type: 'doc', id: 'infractions/disjoncteur-differentiel-non-fonctionnel', label: 'Disjoncteur Différentiel Non Fonctionnel' },
        { type: 'doc', id: 'infractions/liaisons-equipotentielles-non-realisees', label: 'Liaisons Équipotentielles Non Réalisées' },
        { type: 'doc', id: 'infractions/circuits-mixtes-non-conformes', label: 'Circuits Mixtes Non Conformes' },
        { type: 'doc', id: 'infractions/absence-terre-sur-prises', label: 'Absence de Terre sur Prises à Broches de Terre' },
        { type: 'doc', id: 'infractions/installation-non-realisee-regles-art', label: 'Installation Non Réalisée Selon les Règles de l\'Art' },
        { type: 'doc', id: 'infractions/degres-protection-non-respectes', label: 'Degrés de Protection Non Respectés' },
        { type: 'doc', id: 'infractions/conclusion', label: 'Conclusion' },
      ],
    },
  ],
};

// Exportation de l'objet sidebars
module.exports = sidebars;
